// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebCondominio.Residencial.Context;

namespace WebCondominio.Residencial.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20210622231912_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("WebCondominio.Residencial.Models.Inquilino", b =>
                {
                    b.Property<int>("IdInquilino")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumeroContrato")
                        .HasColumnType("TEXT");

                    b.HasKey("IdInquilino");

                    b.ToTable("Inquilino");
                });

            modelBuilder.Entity("WebCondominio.Residencial.Models.Morador", b =>
                {
                    b.Property<int>("IdMorador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apartamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bloco")
                        .HasColumnType("TEXT");

                    b.Property<int?>("InquilinoIdInquilino")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PessoaIdPessoa")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProprietarioIdProprietario")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdMorador");

                    b.HasIndex("InquilinoIdInquilino");

                    b.HasIndex("PessoaIdPessoa");

                    b.HasIndex("ProprietarioIdProprietario");

                    b.ToTable("Contatos");
                });

            modelBuilder.Entity("WebCondominio.Residencial.Models.Pessoa", b =>
                {
                    b.Property<int>("IdPessoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rg")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sexo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone3")
                        .HasColumnType("TEXT");

                    b.HasKey("IdPessoa");

                    b.ToTable("Pessoa");
                });

            modelBuilder.Entity("WebCondominio.Residencial.Models.Proprietario", b =>
                {
                    b.Property<int>("IdProprietario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumeroMatricula")
                        .HasColumnType("TEXT");

                    b.HasKey("IdProprietario");

                    b.ToTable("Proprietario");
                });

            modelBuilder.Entity("WebCondominio.Residencial.Models.Veiculo", b =>
                {
                    b.Property<int>("IdVeiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ano")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Marca")
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MoradorIdMorador")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Placa")
                        .HasColumnType("TEXT");

                    b.HasKey("IdVeiculo");

                    b.HasIndex("MoradorIdMorador");

                    b.ToTable("Veiculo");
                });

            modelBuilder.Entity("WebCondominio.Residencial.Models.Morador", b =>
                {
                    b.HasOne("WebCondominio.Residencial.Models.Inquilino", "Inquilino")
                        .WithMany()
                        .HasForeignKey("InquilinoIdInquilino");

                    b.HasOne("WebCondominio.Residencial.Models.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaIdPessoa");

                    b.HasOne("WebCondominio.Residencial.Models.Proprietario", "Proprietario")
                        .WithMany()
                        .HasForeignKey("ProprietarioIdProprietario");

                    b.Navigation("Inquilino");

                    b.Navigation("Pessoa");

                    b.Navigation("Proprietario");
                });

            modelBuilder.Entity("WebCondominio.Residencial.Models.Veiculo", b =>
                {
                    b.HasOne("WebCondominio.Residencial.Models.Morador", null)
                        .WithMany("Veiculos")
                        .HasForeignKey("MoradorIdMorador");
                });

            modelBuilder.Entity("WebCondominio.Residencial.Models.Morador", b =>
                {
                    b.Navigation("Veiculos");
                });
#pragma warning restore 612, 618
        }
    }
}
